// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDK-xzcPw8CiagLsu6hoPTiFJuukqG34',
    appId: '1:904189940831:web:101c7c4fdbb762bde9f7ea',
    messagingSenderId: '904189940831',
    projectId: 'proyecto-aa-d3669',
    authDomain: 'proyecto-aa-d3669.firebaseapp.com',
    storageBucket: 'proyecto-aa-d3669.firebasestorage.app',
    measurementId: 'G-3KVC4DV1H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6GNF-Kn5yVE97DYrAfKgG4_npZWq1eE8',
    appId: '1:904189940831:android:4b64bdd757b580dee9f7ea',
    messagingSenderId: '904189940831',
    projectId: 'proyecto-aa-d3669',
    storageBucket: 'proyecto-aa-d3669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVBqYAU4fYFb6sOVqy8lGfAanrabyVo4',
    appId: '1:904189940831:ios:d1c7e4598275d5f7e9f7ea',
    messagingSenderId: '904189940831',
    projectId: 'proyecto-aa-d3669',
    storageBucket: 'proyecto-aa-d3669.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEVBqYAU4fYFb6sOVqy8lGfAanrabyVo4',
    appId: '1:904189940831:ios:d1c7e4598275d5f7e9f7ea',
    messagingSenderId: '904189940831',
    projectId: 'proyecto-aa-d3669',
    storageBucket: 'proyecto-aa-d3669.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdDK-xzcPw8CiagLsu6hoPTiFJuukqG34',
    appId: '1:904189940831:web:0e51696652a96c87e9f7ea',
    messagingSenderId: '904189940831',
    projectId: 'proyecto-aa-d3669',
    authDomain: 'proyecto-aa-d3669.firebaseapp.com',
    storageBucket: 'proyecto-aa-d3669.firebasestorage.app',
    measurementId: 'G-KL0N8EKDSG',
  );
}
